### PR TITLE
Change require to path relative load.

### PR DESCRIPTION
**Pull request by phillord**

### CODE REVIEW

**Comment by rocky** [comment]
Were you going to extend the Commentary section to include a descriptions of the new funcitons? Not a big deal,  but should be done at some point.

**Comment by phillord** [comment]
Sorry -- thought you meant the readme. Added that also.

**Comment by rocky** [comment]
Sorry for the delay. Your code has been pushed to elpa now. Within a day it
should be available from that as well as github and melpa.

Again, thanks for all of the help.

**Comment by phillord** [comment]
Ta!

**Pull request merged**
